csk/urls.py
from django.urls import path
from csk.views import *
app_name='something'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

mi/urls.py
from django.urls import path
from mi.views import *
app_name='nothing'
urlpatterns=[
    path('rohit/',rohit,name='rohit'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,mi

urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('mi/',include('mi.urls')),
]

csk/models.py
from django.db import models

# Create your models here.

mi/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')

mi/views.py
from django.shortcuts import render

# Create your views here.
def rohit(request):
    return render(request,'rohit.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to dhoni html page</h1>
        <a href="{% url 'nothing:rohit' %}">navigate to rohit page</a>
    </center>
    
</body>
</html>

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            welcome to rohit html page
        </h1>
        <a href="{% url 'something:dhoni' %}">navigate to dhoni page</a>
    </center>
    
</body>
</html>